services:
  web:
    build: .
    ports:
      - "10110:5000"
    environment:
      FLASK_ENV: production
      MYSQL_HOST: db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
      MYSQL_DATABASE: flask_app
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/shared
    depends_on:
      db:
        condition: service_healthy
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.game.rule=Host(`gamediver.de`)"
      - "traefik.http.routers.game.entrypoints=web-secure"
      - "traefik.http.routers.game.tls=true"
      - "traefik.http.routers.game.tls.certresolver=cloudflare"
      - "traefik.http.routers.game.tls.domains[2].main=gamediver.de"
      - "traefik.http.routers.game.service=gameService"
      - "traefik.http.services.gameService.loadBalancer.server.port=5000"

  db:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "10111:10111"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_data:/docker-entrypoint-initdb.d
    networks:
      - main
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 180s

volumes:
  mysql_data:

networks:
  main:
    external: true
